### ISSUE TITLE
NYU Test data

### ISSUE THREAD

**Issue by Waynechen92** [ENSTA-U2IS/LDU#6]
Hi,

The test file for nyu dataset, has unclear file path, which makes testing unavaliable.
For example, in the file 'nyudepthv2_test_files_with_gt.txt', the first row is: bathroom/rgb_00045.jpg bathroom/sync_depth_00045.png 518.8579;
However, there is no such folder named bathroom, in the sync dataset you provided. 
Would you mind giving me a bit hint on that?

Thanks
Wayne

**Comment by xuanlongORZ** [comment]
Hi,

Yes, this is an oversight, as we did not train and evaluate on NYU, so some steps are missing.
If you need to evaluate on NYU, you need to download another dataset, 'sync' is used for training. The experiment is based on BTS repo so you can refer to https://github.com/cleinc/bts/tree/master/pytorch#testing-with-nyu-depth-v2 for specific steps. 
Hope this helps you.
Xuanlong

**Comment by Waynechen92** [comment]
Hi Xuanlong,

Thanks for your reply, I will follow the steps in BTS.

Best regards,
Wayne
